apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-master
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  containers:
  - name: test-container-3
    image: kssamwang/gx-plug:v3.0-GraphX
    command: ["bash", "-c", "sleep 86400"]
    resources:
      limits:
        nvidia.com/gpu: 1 # 请求1个vGPUs
        nvidia.com/gpumem: 30000 # 每个vGPU申请3000m显存 （可选，整数类型）
        nvidia.com/gpucores: 90 # 每个vGPU的算力为30%实际显卡的算力 （可选，整数类型）
