apiVersion: v1
kind: Service
metadata:
  labels:
    app: nvidia-gpu-exporter
  name: nvidia-gpu-exporter
  namespace: monitoring
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9835
    targetPort: http
  type: ClusterIP
