apiVersion: v1
kind: Endpoints
metadata:
  name: nvidia-gpu-exporter
  namespace: monitoring
subsets:
  - addresses: 
    - ip: 172.17.16.4
    - ip: 172.17.16.17 # 直接这样添加集群中各个主机的内网IP
    ports:
    - name: http
      port: 9835
      protocol: TCP
